export const SEARCH_FLIGHTS = 'SEARCH_FLIGHTS';

export const FETCH_FLIGHTS_START = 'FETCH_FLIGHTS_START';
export const FETCH_FLIGHTS_SUCCESS = 'FETCH_FLIGHTS_SUCCESS';
export const FETCH_FLIGHTS_FAILURE = 'FETCH_FLIGHTS_FAILURE';

export const SET_BOOKING_FLIGHT = 'SET_BOOKING_FLIGHT';
export const SET_PASSENGER_DETAILS = 'SET_PASSENGER_DETAILS';
export const SET_PREFERENCES = 'SET_PREFERENCES';
export const SET_STEP_SUCCESS = 'SET_STEP_SUCCESS';

export const CANCEL_BOOKING = 'CANCEL_BOOKING';
export const STEP_BACK = 'STEP_BACK';
